# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf1b3c5cfe1364c7a28955e98b06e6b9fd582d6fa7a0b86e1095b11fc21090150e65e4ceee1fe628496d2f6f67b6f5aa4db4643d79994f2e33b78dbd75eba04d

test:
  secret_key_base: 932e37396ddc05e2e16d21034810ff8ba8547c4accecd81017ab37f219231940547d0767486f73797b94981eddedcc46b70ea67a85429ca29a32312a10a47bb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
